/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LandAgreementRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createAgreement"
      | "getAgreement"
      | "getAgreementStatus"
      | "getUserAgreements"
      | "hasSignedAgreement"
      | "owner"
      | "revokeAgreement"
      | "signAgreement"
      | "totalAgreements"
      | "updateDocument"
      | "verifyDocumentCid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementCreated"
      | "AgreementRevoked"
      | "AgreementSigned"
      | "DocumentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      string,
      string,
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreementStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAgreements",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignedAgreement",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signAgreement",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgreements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocument",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocumentCid",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreementStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAgreements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSignedAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgreements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocumentCid",
    data: BytesLike
  ): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    creator: AddressLike,
    farmer1UserId: string,
    farmer2UserId: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    creator: string,
    farmer1UserId: string,
    farmer2UserId: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    creator: string;
    farmer1UserId: string;
    farmer2UserId: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementRevokedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    revokedBy: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    revokedBy: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    revokedBy: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementSignedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    signer: AddressLike,
    signerRole: string,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    signer: string,
    signerRole: string,
    newStatus: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    signer: string;
    signerRole: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentUpdatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    documentCid: string,
    metadataCid: string
  ];
  export type OutputTuple = [
    agreementId: string,
    documentCid: string,
    metadataCid: string
  ];
  export interface OutputObject {
    agreementId: string;
    documentCid: string;
    metadataCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandAgreementRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandAgreementRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandAgreementRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAgreement: TypedContractMethod<
    [
      farmer1UserId: string,
      farmer1Name: string,
      farmer1Address: AddressLike,
      farmer1Survey: string,
      farmer1Centiacres: BigNumberish,
      farmer1SharePercent: BigNumberish,
      farmer2UserId: string,
      farmer2Name: string,
      farmer2Address: AddressLike,
      farmer2Survey: string,
      farmer2Centiacres: BigNumberish,
      farmer2SharePercent: BigNumberish,
      startTs: BigNumberish,
      endTs: BigNumberish,
      documentCid: string
    ],
    [string],
    "nonpayable"
  >;

  getAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        creator: string;
        farmer1Name: string;
        farmer1UserId: string;
        farmer1Centiacres: bigint;
        farmer1Share: bigint;
        farmer2Name: string;
        farmer2UserId: string;
        farmer2Centiacres: bigint;
        farmer2Share: bigint;
        documentCid: string;
        status: bigint;
        signatureCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getAgreementStatus: TypedContractMethod<
    [agreementId: BytesLike],
    [bigint],
    "view"
  >;

  getUserAgreements: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  hasSignedAgreement: TypedContractMethod<
    [agreementId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  revokeAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [void],
    "nonpayable"
  >;

  signAgreement: TypedContractMethod<
    [agreementId: BytesLike, farmerAddress: AddressLike, signerName: string],
    [void],
    "nonpayable"
  >;

  totalAgreements: TypedContractMethod<[], [bigint], "view">;

  updateDocument: TypedContractMethod<
    [agreementId: BytesLike, documentCid: string, metadataCid: string],
    [void],
    "nonpayable"
  >;

  verifyDocumentCid: TypedContractMethod<
    [agreementId: BytesLike, cid: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      farmer1UserId: string,
      farmer1Name: string,
      farmer1Address: AddressLike,
      farmer1Survey: string,
      farmer1Centiacres: BigNumberish,
      farmer1SharePercent: BigNumberish,
      farmer2UserId: string,
      farmer2Name: string,
      farmer2Address: AddressLike,
      farmer2Survey: string,
      farmer2Centiacres: BigNumberish,
      farmer2SharePercent: BigNumberish,
      startTs: BigNumberish,
      endTs: BigNumberish,
      documentCid: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        creator: string;
        farmer1Name: string;
        farmer1UserId: string;
        farmer1Centiacres: bigint;
        farmer1Share: bigint;
        farmer2Name: string;
        farmer2UserId: string;
        farmer2Centiacres: bigint;
        farmer2Share: bigint;
        documentCid: string;
        status: bigint;
        signatureCount: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgreementStatus"
  ): TypedContractMethod<[agreementId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAgreements"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasSignedAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeAgreement"
  ): TypedContractMethod<[agreementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, farmerAddress: AddressLike, signerName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgreements"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateDocument"
  ): TypedContractMethod<
    [agreementId: BytesLike, documentCid: string, metadataCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocumentCid"
  ): TypedContractMethod<
    [agreementId: BytesLike, cid: string],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementRevoked"
  ): TypedContractEvent<
    AgreementRevokedEvent.InputTuple,
    AgreementRevokedEvent.OutputTuple,
    AgreementRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementSigned"
  ): TypedContractEvent<
    AgreementSignedEvent.InputTuple,
    AgreementSignedEvent.OutputTuple,
    AgreementSignedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentUpdated"
  ): TypedContractEvent<
    DocumentUpdatedEvent.InputTuple,
    DocumentUpdatedEvent.OutputTuple,
    DocumentUpdatedEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(bytes32,address,string,string,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementRevoked(bytes32,address,uint256)": TypedContractEvent<
      AgreementRevokedEvent.InputTuple,
      AgreementRevokedEvent.OutputTuple,
      AgreementRevokedEvent.OutputObject
    >;
    AgreementRevoked: TypedContractEvent<
      AgreementRevokedEvent.InputTuple,
      AgreementRevokedEvent.OutputTuple,
      AgreementRevokedEvent.OutputObject
    >;

    "AgreementSigned(bytes32,address,string,uint8)": TypedContractEvent<
      AgreementSignedEvent.InputTuple,
      AgreementSignedEvent.OutputTuple,
      AgreementSignedEvent.OutputObject
    >;
    AgreementSigned: TypedContractEvent<
      AgreementSignedEvent.InputTuple,
      AgreementSignedEvent.OutputTuple,
      AgreementSignedEvent.OutputObject
    >;

    "DocumentUpdated(bytes32,string,string)": TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;
    DocumentUpdated: TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;
  };
}
